---

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart plex
  service:
    name: plexmediaserver
    state: restarted

- name: restart sabnzbd
  service:
    name: sabnzbd
    state: restarted

- name: restart sonarr
  service:
    name: sonarr
    state: restarted

- name: restart radarr
  service:
    name: radarr
    state: restarted

- name: restart tautulli
  service:
    name: tautulli
    state: restarted

- name: restart ombi
  service:
    name: ombi
    state: restarted
