---
- name: Converge
  hosts: all
  vars:
    httpauth_pass: Password123
    plex_url: https://plex.acme.corp
    plex_token: gibberishtoken
    plex_api_key: gibberishapikey
    movie_library_id: 69
    test: true
    base_domain: youreabigguy.org
    ombi_domain: "ombi.{{ base_domain }}"
    plex_domain: "plex.{{ base_domain }}"
    sabnzbd_domain: "sabnzbd.{{ base_domain }}"
    radarr_domain: "radarr.{{ base_domain }}"
    sonarr_domain: "sonarr.{{ base_domain }}"
    tautulli_domain: "tautulli.{{ base_domain }}"
    transmission_domain: "transmission.{{ base_domain }}"
  roles:
    - media-ansible/roles/common
    - media-ansible/roles/systemd
    - media-ansible/roles/packages
    - media-ansible/roles/webservices
